from environs import Env

env = Env()
env.read_env()

PROCESS_PUBSUB_MESSAGES_IN_BACKGROUND = env.bool("PROCESS_PUBSUB_MESSAGES_IN_BACKGROUND", True)
MAX_OBSERVATIONS_TO_SEND = env.int("MAX_OBSERVATIONS_TO_SEND", 100)
